# BASE UI
ColorColumn: '' #no
Conceal: '' #no
Cursor: 'pale-lavender'
CursorIM: ''
CursorColumn: ''
CursorLine: '- deep-blue-gray'
CursorLineNr: 'light-gray'
Directory: '' #no
DiffAdd: ''
DiffChange: ''
DiffDelete: ''
DiffText: ''
ErrorMsg: ''
VertSplit: '- blue-black'
Folded: '' #no
FoldColumn: '- blue-black'
SignColumn: '- blue-black'
IncSearch: '' #no
LineNr: 'med-dark-gray'
MatchParen: '' #no
ModeMsg: '- blue-black'
MoreMsg: '- blue-black'
NonText: '' #no
Normal: 'off-white dark-blue-gray'
PMenu: '- blue-black'
PMenuSel: '- blue-black'
PmenuSbar: '- blue-black'
PmenuThumb: '- blue-black'
Question: '- blue-black'
Search: '- blue-black'
SpecialKey: '- blue-black'
SpellBad: ''
SpellLocal: ''
SpellCap: ''
SpellRare: ''
StatusLine: 'deep-blue-gray blue-black'
StatusLineNC: '- blue-black'
TabLine: '- blue-black'
TabLineFill: '- blue-black'
TabLineSel: '- blue-black'
Title: '- blue-black'
Visual: '- dim-blue-gray'
VisualNOS: '- blue-black'
WarningMsg: '- blue-black'
WildMenu: '- blue-black'
# BASE SYNTAX
Comment: 'comment-gray'
Constant: 'pale-lavender'
String: 'string-taupe' # Constant
Character: 'off-white' # Constant
Boolean: 'med-pink' # Constant
Number: 'pale-orange' # Constant
Float: 'pale-orange' # Constant
Identifier: 'bright-pink'
Function: 'light-green' # Identifier
Statement: 'bright-pink'
Conditional: 'bright-pink' # Statement
Repeat: 'bright-pink' # Statement
Label: 'yellow-white' # Statement
Operator: 'med-pink' # Statement
Keyword: 'bright-pink' # Statement
Exception: 'orange-pink' # Statement
PreProc: 'orange-yellow'
Include: 'dusky-pink' # PreProc
Define: 'dusky-pink' # PreProc
Macro: 'dusky-pink' # PreProc
PreCondit: 'dusky-pink' # PreProc
Type: 'light-blue'
StorageClass: '' # Type
Structure: '' # Type
Typedef: '' # Type
Special: ''
SpecialChar: '' # Special
Tag: '' # Special
Delimiter: '' # Special
SpecialComment: '' # Special
Debug: '' # Special
Underlined: ''
Ignore: ''
Error: ''
Todo: ''
